Manual input test
Code-the-Dream-School/health-keeper pull request #23
Opened 2024-12-14 07:03 UTC by VoldemLive

# Manual Input Blood Test Results Feature

## Features
1. Create new blood test with:
   - Biomarker selection
   - Value input
   - Automatic reference range assignment
   - Automatic unit assignment
   - Optional notes
   - Patient selection (for users with full access)

2. Validation rules:
   - Value must be non-negative
   - Value must be numeric
   - Biomarker must be selected
   - Reference range must exist
   - Unit must be present

3. UI Features:
   - Dynamic reference range display
   - Error messages display
   - Success messages after creation
   - Form field validation indicators

## Test Plan
1. Unit Tests:
   - Model validations for LabTest
   - Associations between models
   - Value validation (negative, zero, positive, non-numeric)
   - Required field validations

2. Integration Tests:
   - Successful blood test creation
   - Error handling for invalid inputs
   - Form submission with all required fields
   - JavaScript-dependent functionality

3. Feature Tests:
   - Complete form submission workflow
   - Dynamic field updates
   - Error message display
   - Success message display
   - Patient selection for authorized users

4. Edge Cases:
   - Boundary values for reference ranges
   - Special characters in inputs
   - Zero and negative values
   - Missing required fields
   - Invalid biomarker selections
   
   
   --------------
TEST RESULTS:

...Capybara starting Puma...
* Version 6.4.3, codename: The Eagle of Durango
* Min threads: 0, max threads: 4
* Listening on http://127.0.0.1:64570
.....................

Finished in 5.04 seconds (files took 1.7 seconds to load)
24 examples, 0 failures

2024-12-18 06:46 UTC, aksafan requested changes
Well done with the task and tests!

Please look at comments, especially about "Blood" test naming and SOLID.
Also, please target `develop` as a branch for all feature requests.

2024-12-18 06:46 UTC, aksafan commented on .DS_Store
Please add OS specific files to `.gitignore`.

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +  SuggestExtensions: false
Any specific reason for this to be disabled?

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +    - "app/controllers/**/*"
Please kindly specify the exact reason for increasing MethodLength and excluding all Controllers from the check.

This seems to be a code smell marker if you need to remove this check. Potentially breaking Single responsibility principle.

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +  Enabled: false
This should not be disabled for all the project. If you have a great need, than please disable it in the target file.

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +    - "spec/**/*"
This looks the same as for `Metrics/MethodLength` and Controllers above.
Potentially shows too complex logic and breaking Single responsibility principle.

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +  Enabled: false
This could be fixed in code without disabling Rubocop rule (e.g. like [here](https://github.com/Code-the-Dream-School/health-keeper/blob/main/app/controllers/lab_tests_controller.rb#L71)).

2024-12-18 06:46 UTC, aksafan commented on .vscode/settings.json
> +}
```suggestion
}

```

2024-12-18 06:46 UTC, aksafan commented on .vscode/settings.json
I'm not quite sure if we need Code editor specific settings as not everyone in a team uses VSCode, and not exactly with this color schema.
Thus, please consider adding this to `.gitignore`.

2024-12-18 06:46 UTC, aksafan commented on .rubocop.yml
> +  Enabled: false
Any specific reason to disable this group of checks?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/biomarkers_controller.rb
> +  def reference_ranges
I wonder, why do we have an action returning `reference_ranges` not in `reference_ranges_controller.rb`?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
What we will do if a user wants to add `urinal test` if this one is only for `blood_test`?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = LabTest.new
Why do we create `**lab**_test` inside `new_**blood**_test` action? Seems that the naming is a bit not obvious.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
Why do you have authorization disabled here?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
Why do you have authorization disabled here?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
I wonder why we can't reuse already existed `new` [action](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR25)?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def create_blood_test
I wonder why we can't reuse already existed create [action](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR36)?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        user: current_user.full_access_roles_can? ? User.find(params[:user_id]) : current_user,
This logic looks not transparent and somewhat tricky.
Please consider adding comment or rewriting.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.recordable = @health_record
This should work through relation automatically if building record with ActiveRecord (e.g. [here](https://github.com/Code-the-Dream-School/health-keeper/blob/main/app/controllers/biomarkers_controller.rb#L19)), so you don't need to specify `recordable` manually.

Please consider relying on [Polymorphic Associations](https://guides.rubyonrails.org/association_basics.html#polymorphic-associations) documentation.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.notes = lab_test_params[:notes]
Do we use the same notes for both lab_test and health_record?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      if @lab_test.valid? && @health_record.valid?
AR:save method will call validation anyways, so you don't need this overhead with an additional validation in advance.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def create_blood_test
This method looks like a [God method](https://wiki.c2.com/?GodMethod), in other words: doing to many things in one.

Please consider splitting the business logic.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        @health_record.save!
Please consider using AR [Associations](https://guides.rubyonrails.org/association_basics.html#methods-added-by-belongs-to-assigning-the-association) to link models together and run only one save.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        @health_record.save!
Please consider using `save`. Ref to [this](https://stackoverflow.com/a/5056428) answer.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        redirect_to @health_record and return
Please avoid using `and` as it has [has lower precedence](https://stackoverflow.com/a/1426835) than both `&&` and even `=`.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        render :new_blood_test, status: :unprocessable_entity and return
Please consider using new liner for `return` with `render` and `redirect_to` as it stated in [the official documentation](https://guides.rubyonrails.org/layouts_and_rendering.html#avoiding-double-render-errors).

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +          @selected_biomarker = Biomarker.find(@lab_test.biomarker_id)
Why do you query `biomarker` table here again if you have already had all the biomarkers from the `        @biomarkers = Biomarker.all` above?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      raise ActiveRecord::Rollback unless @lab_test.persisted?
Please consider using explicit interception of ActiveRecord exceptions if using `save!`.
Postponing this check to the `ensure` section makes this not obvious and could potentially lead to unexpected behavior and bugs.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      flash.now[:alert] = 'An error occurred while saving the blood test.'
Why don't we check `if @lab_test.biomarker_id.present?` like we did above?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +        @biomarkers = Biomarker.all
Why do you need to get all biomarkers here again if you have already gotten them [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR129)?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      @biomarkers = Biomarker.all
Why do you need to get all biomarkers here again if you have already gotten them [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR129)?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def blood_test_params
Why you don't reuse already existed `lab_test_params` method?

2024-12-18 06:46 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = current_user.lab_tests.build
Why don't you want to build `lab_test` here?
This is a great `rails` way to split the logic and make it reusable.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
Please, don't skip authorization.

2024-12-18 06:46 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges.map { |range|
Please don't use curly bracers with multi-liners in Ruby, use a`Ruby` way `do...end` syntax instead.

2024-12-18 06:46 UTC, aksafan commented on app/javascript/controllers/biomarker_select_controller.js
> +        this.referenceRangeTarget.textContent = `${range.min_value} - ${range.max_value}`
What will be if `${range.min_value}` and/or `${range.max_value}` are undefined?

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> -  belongs_to :recordable, polymorphic: true, touch: true
Why have you removed `updated_at` attributes updates?
Please consider referring to [the official documentation](https://apidock.com/rails/ActiveRecord/Persistence/touch).

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +                      message: lambda do |_object, data|
Like lambda usage here!

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +                          'must be a non-negative number'
Does `greater_than_or_equal_to` not provide build-in error messages?

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +  # Helper method to check if value is within reference range
`within_reference_range` has pretty straightforward and self-descriptive naming.
Thus, you can omit this comment.

I like that naming btw.

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +    return nil unless value && reference_range
```suggestion
    return nil unless value && reference_range
    
```

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +  # Helper method to get the status of the value
`status` has pretty straightforward and self-descriptive naming.
Thus, you can omit this comment.

2024-12-18 06:46 UTC, aksafan commented on app/models/lab_test.rb
> +  def status
What this status is used for?

Please consider adding constants for these symbols to make them transparent and easy to maintain in the future.
Ref to user roles [here](https://github.com/Code-the-Dream-School/health-keeper/blob/main/app/models/user.rb#L54).

2024-12-18 06:46 UTC, aksafan commented on app/models/user.rb
> +    # has_any_role?(*User::Roles::FULL_ACCESS_ROLES)
Please use previous version of authorization code. It is more transparent and easy to support in the future.

2024-12-18 06:46 UTC, aksafan commented on app/policies/lab_test_policy.rb
> +
Don't forget to remove this if you decide to reuse already existed methods in controller.

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/_form.html.erb
> +<% if lab_test.errors.any? %>
Pretty strange formatting changes as for me. Could you please elaborate the exact purpose of them?

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/_form.html.erb
> +<% end %>
```suggestion
<% end %>

```

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/index.html.erb
> +            <%= link_to "New Blood Test", new_blood_test_lab_tests_path, class: "btn btn-primary" %>
Why do we have two buttons here for the same functionality?

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/index.html.erb
> +    <div id="lab_tests" class="tw-relative tw-overflow-x-auto tw-shadow-md tw-sm:tw-rounded-lg">
We should agreed on amount of spaces for erb files to not add these kind of changes to every PR.

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/index.html.erb
> +</section>
```suggestion
</section>

```

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
Why don't you reuse existed `app/views/lab_tests/new.html.erb`?

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
> +    <h1 class="tw-text-2xl tw-font-bold tw-mb-4">New Blood Test</h1>
```suggestion
    <h1 class="tw-text-2xl tw-font-bold tw-mb-4">New Lab Test</h1>
```

We are working with a LabTest model everywhere. Why do we use Blood test definitions?

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
> +                      options_from_collection_for_select(User.all, :id, :email, params[:user_id]),
Please, don't do DB queries in views.

By definition the Views in MVC are used to show the application information to the user and not to get that information from DB.

Also this approach:
- breaks [SOLID](https://en.wikipedia.org/wiki/SOLID) principles (at least S, O and D),
- breaks [GRASP](https://en.wikipedia.org/wiki/GRASP_(object-oriented_design)) (increasing coupling and lowering cohesion that are anti-patterns by themselves).

Thus, we shouldn't do DB queries inside the views.

Please consider this old but gold [article](http://weblog.jamisbuck.org/2006/10/18/skinny-controller-fat-model) about DB queries in Rails applications.
TLDR: Slim controller and somewhat fat models are much better than opposite, or even worse - DB queries and/or business logic (BL) in views.

Of course, even better would be to separate concerns and for example extract BL into services and keeping complex DB queries out of the models as well, or even to introduce a [Presenter](https://samvera.github.io/patterns-presenters.html) pattern to make controllers even slimmer. 
You decide.

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
> +                { class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:biomarker_id].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}",
What will be if `:biomarker_id` is empty or does not exist?

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
> +                    <%= @selected_biomarker&.reference_ranges&.first ?
Please consider avoiding usage of multi-line ternary operator. It increases cognitive load of reading code and make thins not obvious.
Use if-else instead.

2024-12-18 06:46 UTC, aksafan commented on app/views/lab_tests/new_blood_test.html.erb
> +                    class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:value].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}"
What will be if `:value` is empty or does not exist?

2024-12-18 06:46 UTC, aksafan commented on db/seeds.rb
> +Rails.logger.debug 'Seeding completed successfully!'
This will prevent information to be displayed in console when running seeding in docker. 
A [workaround](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-4f894049af3375c2bd4e608f546f8d4a0eed95464efcdea850993200db9fef5cR19) is added to avoid Rubocop warnings.

2024-12-18 06:46 UTC, aksafan commented on spec/controllers/lab_tests_controller_spec.rb
> +  describe 'POST #create_blood_test' do
Do you have plans to add at least one more successful case?

2024-12-19 05:41 UTC, VoldemLive commented on .DS_Store
done, .DS_Store file added into .gitignore.

2024-12-26 23:42 UTC, aksafan commented on .DS_Store
Great job! 

Now, please make sure you also remove `.DS_Store` [file](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-e2eb93a61ffd7877ea5c751abcb3a618e8e2e9a2073a27f66d4114fe10819f86) from this PR.

2024-12-26 23:45 UTC, aksafan commented on .DS_Store
Adding a file/folder to `.gitignore` usually means both adding a record to `.gitignore` and removing the file itself from git (PR).

2024-12-26 23:45 UTC, aksafan commented on .vscode/settings.json
Please make sure you also remove [.vscode/settings.json](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-a5de3e5871ffcc383a2294845bd3df25d3eeff6c29ad46e3a396577c413bf357) from this PR in addition to adding it to `.gitignore`.

Adding a file/folder to `.gitignore` usually means both adding a record to `.gitignore` and removing the file itself from git (PR).

2024-12-27 00:54 UTC, aksafan reviewed
Well done in LabTest controller.
Almost ready for being approved.

Please make sure to answer and cover all comments left.

2024-12-27 00:54 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> -    @lab_test = current_user.lab_tests.build(lab_test_params)
Why have you removed this method and add this line to the [action](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR36)?

It was extracted from the method on purpose to support Single responsibility and decrease cognitive load.
Please consider moving this back.

2024-12-27 00:54 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def save_records
The name of this method doesn't show the exact sense of what is going on inside.
What exact records are we saving?
How to determine from the name, that both `health_record` and `lab_test` records suppose to be saved?

I'm not quite sure if we even need to extract this functionality to a separate method.
If you still want, than please consider renaming it to display the exact functionality behind this method.

2024-12-27 00:54 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
```suggestion
  def get_user
```

Simpler and much more common naming for this kind of logic.

2024-12-27 00:54 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.recordable = @health_record
Have you tried do this with a relation while you are already building a LabTest model, like I said in my [previous comment](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1887950605) about this line?

2024-12-27 00:54 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    @selected_biomarker = Biomarker.find(@lab_test.biomarker_id)
Why do you query biomarker table here again if you have already had all the biomarkers from the         @biomarkers = Biomarker.all [below](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR114)?

2024-12-27 00:54 UTC, aksafan commented on app/javascript/controllers/biomarker_select_controller.js
> +        this.referenceRangeTarget.textContent = `${minValue} - ${maxValue}`
So now it could be `- - -` value inside `this.referenceRangeTarget.textContent`, couldn't it?
Does it look a bit strange?

2024-12-27 00:54 UTC, aksafan commented on app/policies/lab_test_policy.rb
> +    create?
You don't need this as it is set by default in [application_policy.rb](https://github.com/Code-the-Dream-School/health-keeper/blob/main/app/policies/application_policy.rb#L24) that `lab_test_policy.rb` is inherited from.

2024-12-27 00:54 UTC, aksafan commented on app/views/lab_tests/new.html.erb
> +                      options_from_collection_for_select(User.all, :id, :email, params[:user_id]),
Please read my comment about DB queries in views [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1889687972).

2024-12-27 00:54 UTC, aksafan commented on app/views/lab_tests/new.html.erb
> +                { class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:biomarker_id].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}",
What will be if :biomarker_id is empty or does not exist?

2024-12-27 00:54 UTC, aksafan commented on app/views/lab_tests/new.html.erb
> +                    class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:value].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}"
What will be if :value is empty or does not exist?

2024-12-27 00:54 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
Why have you removed this?

2024-12-27 03:58 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
You don't need to call `set_biomarkers` here as it was already called on [before_action](https://github.com/Code-the-Dream-School/health-keeper/pull/23/commits/e0eee2ca2c66870e99e783e21369193ae4232b18#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR5).

2024-12-27 03:58 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    build_lab_test
Don't call it explicitly, user before_action instead, as it was [there](https://github.com/Code-the-Dream-School/health-keeper/blob/main/app/controllers/lab_tests_controller.rb#L5) before.

2024-12-27 03:58 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
```suggestion
```

2024-12-27 03:58 UTC, aksafan commented on app/models/lab_test.rb
> +  module Status
I don't think we need a module here. These Statuses are tight to LabTest class, so nested class would be enough.

2024-12-27 03:58 UTC, aksafan commented on config/routes.rb
> +  resources :reference_ranges, only: %i[show new create edit update destroy]
I didn't get these changes.
Why do we have all reference_ranges actions nested under biomarkers and 6 reference_ranges actions duplicated as not nested ones?

2024-12-27 03:58 UTC, aksafan commented on spec/models/lab_test_spec.rb
> +      #   lab_test.value = -1
Try to change a LabTest value validator to:
```
  validates :value, presence: true, inclusion: { in: 0..10_000 }
```

or
```
validates :value, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10_000 }
```

2024-12-27 20:36 UTC, VoldemLive commented on .rubocop.yml
> +  SuggestExtensions: false
we don't need RuboCop suggesting more extensions - it would just add noise to our output. It's a quality-of-life setting that makes RuboCop's output cleaner and more focused on actual code issues.

2024-12-27 20:36 UTC, VoldemLive commented on .vscode/settings.json
ok, done.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/biomarkers_controller.rb
> +  def reference_ranges
You're right! This is a good catch. This action should indeed be in the reference_ranges_controller.rb

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
I had disabled this authorization check earlier while it was being resolved in the develop branch. Now, I am enabling it again.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
I had disabled this authorization check earlier while it was being resolved in the develop branch. Now, I am enabling it again.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
You are right. We dpn't need additional blood test if we already have new lab test method. I was merged methods and views to one lab test.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
fixed. Now we use just one method new.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = LabTest.new
got it and fixed.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def create_blood_test
fixed

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        user: current_user.full_access_roles_can? ? User.find(params[:user_id]) : current_user,
got it, rewrited.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.recordable = @health_record
I improved this code by making better use of Rails' polymorphic associations.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.notes = lab_test_params[:notes]
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      if @lab_test.valid? && @health_record.valid?
got it and fixed

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        @health_record.save!
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
rewrited. And now I merged blood tests methods and views into single lab test

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def new_blood_test
got it and I used it.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def create_blood_test
got it.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def create_blood_test
got it.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        user: current_user.full_access_roles_can? ? User.find(params[:user_id]) : current_user,
rewrited.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.notes = lab_test_params[:notes]
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      if @lab_test.valid? && @health_record.valid?
fixed

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        redirect_to @health_record and return
got it

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        @health_record.save!
fixed.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        @health_record.save!
used it

2024-12-27 20:36 UTC, VoldemLive commented on spec/controllers/lab_tests_controller_spec.rb
> +  describe 'POST #create_blood_test' do
rewrited to use a lab tests

2024-12-27 20:36 UTC, VoldemLive commented on db/seeds.rb
> +Rails.logger.debug 'Seeding completed successfully!'
changed it back to puts

2024-12-27 20:36 UTC, VoldemLive commented on config/routes.rb
simplified

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = LabTest.new
got it and rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        @biomarkers = Biomarker.all
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +          @selected_biomarker = Biomarker.find(@lab_test.biomarker_id)
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +        render :new_blood_test, status: :unprocessable_entity and return
got it

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      @biomarkers = Biomarker.all
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      flash.now[:alert] = 'An error occurred while saving the blood test.'
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      raise ActiveRecord::Rollback unless @lab_test.persisted?
rewrited.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def blood_test_params
already reused

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
now I am back using auth code again.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges.map { |range|
got it and I am using do...end syntax

2024-12-27 20:36 UTC, VoldemLive commented on app/javascript/controllers/biomarker_select_controller.js
> +        this.referenceRangeTarget.textContent = `${range.min_value} - ${range.max_value}`
rewrite it to secure code and prevent problems with a undefined. But also this is not math function, this is a just data render.

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> -  belongs_to :recordable, polymorphic: true, touch: true
You are right, I added param touch: true.

2024-12-27 20:36 UTC, VoldemLive commented on app/models/user.rb
> +    # has_any_role?(*User::Roles::FULL_ACCESS_ROLES)
I am back to previous version.

2024-12-27 20:36 UTC, VoldemLive commented on app/policies/lab_test_policy.rb
> +
done

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/_form.html.erb
> +<% if lab_test.errors.any? %>
rewrited

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/index.html.erb
> +            <%= link_to "New Blood Test", new_blood_test_lab_tests_path, class: "btn btn-primary" %>
fixed

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/new_blood_test.html.erb
done

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> -    @lab_test = current_user.lab_tests.build(lab_test_params)
I restore this method and used it in create method also `  def create
    build_lab_test ...`

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def save_records
changed method name to the more clear name 
save_health_record_with_lab_test

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
the method determine_user is better because it shows there is logic and decisions involved, and it fits Ruby's style of using clear names. The method get_user is less preferred because "get" is not common in Ruby, it doesn't show there is logic, and it sounds like a simple accessor. But, sure I can rename it, if you want.

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    @selected_biomarker = Biomarker.find(@lab_test.biomarker_id)
fixed, I reused var @biomarkers

2024-12-27 20:36 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +      @lab_test.recordable = @health_record
hope I'm understand you ... and used build_recordable

2024-12-27 20:36 UTC, VoldemLive commented on app/javascript/controllers/biomarker_select_controller.js
> +        this.referenceRangeTarget.textContent = `${minValue} - ${maxValue}`
hmmm, I think about it will be rendered as a - mg/ml - - mg/ml. Maybe 'N/A' or '?' or 'unknown' or leave it empty, it's also look good. So, I set it as '?' for now, tomorrow we will decide final value.

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> +                          'must be a non-negative number'
Yeah, You are right, numericality: { greater_than_or_equal_to: 0 } completely enough

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> +  # Helper method to check if value is within reference range
done

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> +  # Helper method to get the status of the value
done

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> +  def status
I added statuses: low, normal, and high. They are selected based on lab test results.

2024-12-27 20:36 UTC, VoldemLive commented on app/policies/lab_test_policy.rb
> +    create?
done, deleted

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/index.html.erb
> +    <div id="lab_tests" class="tw-relative tw-overflow-x-auto tw-shadow-md tw-sm:tw-rounded-lg">
You are right, let's talk about it next meeting.

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/new.html.erb
> +                      options_from_collection_for_select(User.all, :id, :email, params[:user_id]),
moved db query to controller

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/new.html.erb
> +                { class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:biomarker_id].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}",
added validation and errors handling

2024-12-27 20:36 UTC, VoldemLive commented on app/views/lab_tests/new.html.erb
> +                    class: "tw-mt-1 tw-block tw-w-full tw-rounded-md #{@lab_test.errors[:value].present? ? 'tw-border-red-500' : 'tw-border-gray-300'}"
protect it in model

2024-12-27 20:36 UTC, VoldemLive commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
you are right, I restored this

2024-12-27 20:36 UTC, VoldemLive commented on app/models/lab_test.rb
> +                          'must be a non-negative number'
very strange, but I can't pass for negative value, so comment this part in test to discuss about it next meeting.
and leave this version:
`  validates :value, presence: true,
                    numericality: {
                      in: 0..Float::INFINITY
                    }`

2025-01-04 00:05 UTC, aksafan reviewed
Well done on fixes!

2025-01-04 00:05 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
Agreed with getter in Rails.

Than it should be `set_user`, if you want make it "Rails way".

2025-01-04 00:05 UTC, aksafan commented on config/locales/en.yml
> +              must_be_nonnegative_and_numeric: "value must be nonnegative and as numeric"
```suggestion
              must_be_nonnegative_and_numeric: "The value must be both nonnegative and numeric"
```
More grammatically correct.

2025-01-04 00:05 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
It still shows as removed.

Current state:
![image](https://github.com/user-attachments/assets/0375df98-e05f-4bdb-827b-40d8a91f37c7)

Your changes:
![image](https://github.com/user-attachments/assets/e61013f6-9d66-4a17-9cda-802599c2dd57)

2025-01-04 00:05 UTC, aksafan commented on spec/rails_helper.rb
> +# rubocop:disable RSpec/AnyInstance
Please, don't just remove Rubocop offenses.
They are added by very smart engineers and prevent you from doing a lot of mistakes.

If you need help to address those offenses, feel free to reach me out.

2025-01-04 00:05 UTC, aksafan commented on spec/rails_helper.rb
> +  # Add these lines
```suggestion
```

2025-01-04 00:05 UTC, aksafan commented on spec/rails_helper.rb
> +    allow_any_instance_of(ActionView::Base).to receive(:stylesheet_link_tag).and_return('')
This will impact all the application globally, that is not very good.
This could lead to unexpected issues that will be really difficult to debug.

Changing global state is always bad.

That's why Rubocop shows you `RSpec/AnyInstance` [offense](https://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/AnyInstance) here.
You could fix it as it described there:
```ruby
# bad
describe MyClass do
  before { allow_any_instance_of(MyClass).to receive(:foo) }
end

# good
describe MyClass do
  let(:my_instance) { instance_double(MyClass) }

  before do
    allow(MyClass).to receive(:new).and_return(my_instance)
    allow(my_instance).to receive(:foo)
  end
end
```

2025-01-04 00:05 UTC, aksafan commented on spec/rails_helper.rb
> +Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
Please leave this line as it was [before](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-053aa3ea46cb7c6a649e0d0fc592ce729b66e1d44be475516fd58857ba695862L26) on the line 29 to not brake sequence of comments.

2025-01-04 05:59 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
done

2025-01-04 05:59 UTC, VoldemLive commented on .rubocop.yml
> +    - "app/controllers/**/*"
currently, this file is taken from the branch "develop", so this code is outdated

2025-01-04 05:59 UTC, VoldemLive commented on spec/rails_helper.rb
> +Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
done

2025-01-04 05:59 UTC, VoldemLive commented on spec/rails_helper.rb
> +  # Add these lines
added few variants
`.vscode/
!.vscode/settings.json
### VisualStudioCode ###
.vscode/*      
# Maybe .vscode/**/* instead - see comments
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
# Ignore test files`

it doesn't helps so I deleted it by manual.

2025-01-04 05:59 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
done

2025-01-04 05:59 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
done

2025-01-04 05:59 UTC, VoldemLive commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
it works just with current variant
<img width="793" alt="image" src="https://github.com/user-attachments/assets/ec228fc0-2564-4a18-a459-2fdd8b657c79" />

2025-01-04 05:59 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
no, you are wrong .... I need to back for my var naming. when I tried to pass rubocop I got this:

`Inspecting 98 files
.........C........................................................................................

Offenses:

app/controllers/lab_tests_controller.rb:138:7: C: Naming/AccessorMethodName: Do not prefix reader method names with get_.
  def get_user
      ^^^^^^^^

98 files inspected, 1 offense detected

Tip: Based on detected gems, the following RuboCop extension libraries might be helpful:
  * rubocop-capybara (https://rubygems.org/gems/rubocop-capybara)

You can opt out of this message by adding the following to your config (see https://docs.rubocop.org/rubocop/extensions.html#extension-suggestions for more options):
  AllCops:
    SuggestExtensions: false`

2025-01-04 05:59 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
with a determine_user all passed

2025-01-04 05:59 UTC, VoldemLive commented on spec/rails_helper.rb
> +    allow_any_instance_of(ActionView::Base).to receive(:stylesheet_link_tag).and_return('')
currently I took file from develop branch and all works perfect

2025-01-04 06:31 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
@VoldemLive how it could be done if it is still exist in PR?
![image](https://github.com/user-attachments/assets/a324455c-073c-47e9-992d-7f1cb4e74ffc)

2025-01-04 06:31 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
@VoldemLive didn't get what are you talking about.

I said about SET_user and you tried GET_user and got an error.
Rubocop throws an error about getters, but my point is about another name `set_user`, and NOT `get_user`.

2025-01-04 06:34 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
@VoldemLive okay, but why you did these changes?
What is the reasoning behind them?

2025-01-04 06:40 UTC, aksafan commented on spec/rails_helper.rb
> +Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
@VoldemLive it is not:
![image](https://github.com/user-attachments/assets/ac3afee2-a1dd-4a3f-8b88-7423cec199f3)

2025-01-04 06:42 UTC, VoldemLive commented on spec/rails_helper.rb
> +Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
you answer before I push my last version

2025-01-04 06:44 UTC, aksafan commented on spec/rails_helper.rb
> +  # Add these lines
@VoldemLive you need to physically delete the file from the git.
This is not an issue in your `.gitignore` (it is actually fine).

Please refer to this [post](https://stackoverflow.com/a/13541721) to do that.

2025-01-04 06:51 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
now It's moved to before_action

2025-01-04 06:51 UTC, aksafan commented on .gitignore
> +# Ignore test files
You don't need all of these, your previous variant was okay.

Please look at this [comment](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902579272).

2025-01-04 06:51 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
Please, don't remove authorization.

2025-01-04 06:51 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +# rubocop:disable Metrics/ClassLength
If you add this line, it means that the current class handles to much logic and breaks Single responsibility.

For now let it be, but keep this in mind for the future please.

2025-01-04 06:51 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
Don't remove authentication check here please.
You need to check for `policy_scope` here.

This is the matter of security.

2025-01-04 06:52 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    build_lab_test
rewrited, please check new version

2025-01-04 06:53 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +# rubocop:disable Metrics/ClassLength
ok

2025-01-04 06:53 UTC, aksafan commented on spec/rails_helper.rb
> +Rails.root.glob('spec/support/**/*.rb').each { |f| require f }
He-he, I thought you have done changes before writing a comment.

2025-01-04 06:55 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
ok, I got it and backed it

2025-01-04 06:56 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    # authorize @lab_test
ok, and baked it back

2025-01-04 06:57 UTC, VoldemLive commented on .gitignore
> +# Ignore test files
done, updated with a single line

2025-01-04 06:58 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = LabTest.new(lab_test_params)
You don't need this, you have already had `@lab_test` set from `before_action :build_lab_test, only: %i[create]`, so please remove this.

2025-01-04 07:00 UTC, VoldemLive commented on .DS_Store
it's done.

2025-01-04 07:00 UTC, aksafan commented on .gitignore
> +# Ignore test files
@VoldemLive Perfect!

Now please do the same for `.DS_Store` as mentioned here https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1898148706

2025-01-04 07:03 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +  def determine_user
you are right, with set_user all test are passed

2025-01-04 07:03 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    set_biomarkers
done

2025-01-04 07:05 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
@VoldemLive you are now just rewriting this variable:
![image](https://github.com/user-attachments/assets/96248805-cdc6-4e1b-ad28-85e2754f5e8a)

It can't work in this way.
You need to check authorization explicitly: `@reference_ranges = policy_scope(@biomarker.reference_ranges)`.

```
  def index
    authorize ReferenceRange
    @biomarker = Biomarker.find(params[:biomarker_id])
    @reference_ranges = policy_scope(@biomarker.reference_ranges)
  end

2025-01-04 07:06 UTC, VoldemLive commented on spec/rails_helper.rb
> +  # Add these lines
done, DS_Store deleted from git

2025-01-04 07:07 UTC, aksafan commented on spec/rails_helper.rb
> +  # Add these lines
@VoldemLive Well done!

2025-01-04 07:10 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    @reference_ranges = @biomarker.reference_ranges
you are right, now I have fixed it

2025-01-04 07:10 UTC, VoldemLive commented on .gitignore
> +# Ignore test files
done

2025-01-04 07:13 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    @lab_test = LabTest.new(lab_test_params)
you are right; I deleted it

2025-01-04 07:14 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges
With your current changes, now I don't understand, why do you need this 2 lines?
```
    @biomarker = Biomarker.find(params[:biomarker_id])
    
    render json: @reference_ranges
```
    
`@biomarker` is not used anywhere.
`@reference_ranges` view is rendered by default from index controller.

2025-01-04 07:19 UTC, aksafan commented
@VoldemLive well done with all these fixes!
Keep going!

Only 3 comments left:
- https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902548615
- https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902240402
- https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902654402

2025-01-04 07:21 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges
I argeed about @biomarker, but without render json: @reference_ranges it doesn't work

2025-01-04 07:25 UTC, aksafan commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges
Okay, let it be!

2025-01-04 07:26 UTC, VoldemLive commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
I changed it because reference ranges always need a biomarker to work - like how a child needs a parent. In our controller, we already use biomarker_id to find reference ranges, so our routes should work the same way.

2025-01-04 07:28 UTC, VoldemLive commented on config/locales/en.yml
> +              must_be_nonnegative_and_numeric: "value must be nonnegative and as numeric"
done

2025-01-04 07:36 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
@VoldemLive But it was working the same way as you described before your changes, except for the index action.
So I assume you are using reference_range index action somehow and it doesn't work, does it?

2025-01-04 07:39 UTC, VoldemLive commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
exactly, you are right it doesn't work.

2025-01-04 07:40 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
Found it [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-aeca24437a6ffaa5e03abdd75edc272050fe4b5292559feb9dddffc522938b36R31).
Still, I don't see a place where biomarker_id is used in index action.

2025-01-04 07:41 UTC, aksafan commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
Okay, let it be.

2025-01-04 07:47 UTC, VoldemLive commented on config/routes.rb
> -    resources :reference_ranges, only: %i[show new create edit update destroy]
I need to back my code to this view:
`  def index
    authorize ReferenceRange
    @biomarker = Biomarker.find(params[:biomarker_id])
    @reference_ranges = policy_scope(@biomarker.reference_ranges)
    render json: @reference_ranges
  end`
  
  it works just in this variant, without this line   @biomarker = Biomarker.find(params[:biomarker_id]) it normally update reference ranges. Also, policy_scope(@biomarker.all) didn't works.

2025-01-04 07:52 UTC, VoldemLive commented on app/controllers/reference_ranges_controller.rb
> +    render json: @reference_ranges
I need to back my code to this view:
  def index authorize ReferenceRange @biomarker = Biomarker.find(params[:biomarker_id]) @reference_ranges = policy_scope(@biomarker.reference_ranges) render json: @reference_ranges end

it works just in this variant, without this line @Biomarker = Biomarker.find(params[:biomarker_id]) it normally update reference ranges. Also, policy_scope(@biomarker.all) didn't works.

2025-01-04 07:55 UTC, VoldemLive commented
> @VoldemLive well done with all these fixes! Keep going!
> 
> Only 3 comments left:
> 
> * [Manual input test #23 (comment)](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902548615)
> * [Manual input test #23 (comment)](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902240402)
> * [Manual input test #23 (comment)](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1902654402)


done

2025-01-04 08:12 UTC, aksafan commented
@VoldemLive 

I've pulled your branch and tested functionality a bit.
Got this error while trying to create a Lab test record:
![image](https://github.com/user-attachments/assets/8836a25f-6d9b-44aa-a47b-81f854ca6271)

Used params are on screenshot at the bottom.

2025-01-04 08:14 UTC, VoldemLive commented
> @VoldemLive
> 
> I've pulled your branch and tested functionality a bit. Got this error while trying to create a Lab test record: ![image](https://private-user-images.githubusercontent.com/14964793/400126046-8836a25f-6d9b-44aa-a47b-81f854ca6271.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5Nzg2NjIsIm5iZiI6MTczNTk3ODM2MiwicGF0aCI6Ii8xNDk2NDc5My80MDAxMjYwNDYtODgzNmEyNWYtNmQ5Yi00NGFhLWE0N2ItODFmODU0Y2E2MjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDA4MTI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzNlYTViY2EwMTYxMmUzNzU3MzY4ZmM3MDMzZTBkNWVkYWI5YWVhZDFmOGRmNjJkYzE3Y2Q3NWQwMDdkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7eb3Ka7nZFi3BTRK2nHQ7j5BDMHDlqm2YOoie2qSgAo)
> 
> Used params are on screenshot at the bottom.

but it works perfect on my side 
![image](https://github.com/user-attachments/assets/b74c3aa3-c522-4937-8c9b-3f48fe6762c8)

could you please resetup db

2025-01-04 08:20 UTC, VoldemLive commented
@aksafan I was make additional tests with an adding new lab test after a reinitialization of db and confirmed all works as expected

2025-01-04 08:26 UTC, aksafan commented
w

> @aksafan I was make additional tests with an adding new lab test after a reinitialization of db and confirmed all works as expected

@VoldemLive 

it is broken now:
```
2025-01-04 02:16:03 08:16:03 web.1  | exited with code 1
2025-01-04 02:16:03 08:16:03 system | sending SIGTERM to all processes
2025-01-04 02:16:03 08:16:03 css.1  | exited with code 1
2025-01-04 02:16:36 08:16:36 web.1  | started with pid 14
2025-01-04 02:16:36 08:16:36 css.1  | started with pid 15
2025-01-04 02:16:36 08:16:36 web.1  | /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:600:in `materialize': Could not find pg-1.5.9, puma-6.5.0, importmap-rails-2.0.3, turbo-rails-2.0.11, dotenv-rails-3.1.6, factory_bot_rails-6.4.4, faker-3.5.1, rspec-rails-7.1.0, rubocop-1.69.2, rubocop-rspec-3.3.0, capybara-3.40.0, selenium-webdriver-4.27.0, shoulda-matchers-5.3.0, net-imap-0.5.2, rack-3.1.8, nio4r-2.7.4, msgpack-1.7.5, dotenv-3.1.6, irb-1.14.2, reline-0.6.0, factory_bot-6.5.0, rspec-core-3.13.2, rspec-expectations-3.13.3, rspec-mocks-3.13.2, rspec-support-3.13.2, json-2.9.0, regexp_parser-2.9.3, rubocop-ast-1.37.0, unicode-display_width-3.1.2, addressable-2.8.7, xpath-3.2.0, rexml-3.4.0, rubyzip-2.3.2, websocket-1.2.11, minitest-5.25.4, mutex_m-0.3.0, securerandom-0.4.1, date-3.4.1, timeout-0.4.3, zeitwerk-2.7.1, rackup-2.2.1, execjs-2.10.0, rdoc-6.9.1, io-console-0.8.0, unicode-emoji-4.0.4, public_suffix-6.0.1, psych-5.2.1, stringio-3.1.2 in locally installed gems (Bundler::GemNotFound)
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:193:in `specs'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:259:in `specs_for'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/runtime.rb:18:in `setup'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler.rb:164:in `setup'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/setup.rb:32:in `block in <top (required)>'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/ui/shell.rb:159:in `with_level'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/ui/shell.rb:111:in `silence'
2025-01-04 02:16:36 08:16:36 web.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/setup.rb:32:in `<top (required)>'
2025-01-04 02:16:36 08:16:36 web.1  |   from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
2025-01-04 02:16:36 08:16:36 web.1  |   from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
2025-01-04 02:16:36 08:16:36 web.1  |   from /app/config/boot.rb:5:in `<top (required)>'
2025-01-04 02:16:36 08:16:36 web.1  |   from bin/rails:3:in `require_relative'
2025-01-04 02:16:36 08:16:36 web.1  |   from bin/rails:3:in `<main>'
2025-01-04 02:16:36 08:16:36 css.1  | /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:600:in `materialize': Could not find pg-1.5.9, puma-6.5.0, importmap-rails-2.0.3, turbo-rails-2.0.11, dotenv-rails-3.1.6, factory_bot_rails-6.4.4, faker-3.5.1, rspec-rails-7.1.0, rubocop-1.69.2, rubocop-rspec-3.3.0, capybara-3.40.0, selenium-webdriver-4.27.0, shoulda-matchers-5.3.0, net-imap-0.5.2, rack-3.1.8, nio4r-2.7.4, msgpack-1.7.5, dotenv-3.1.6, irb-1.14.2, reline-0.6.0, factory_bot-6.5.0, rspec-core-3.13.2, rspec-expectations-3.13.3, rspec-mocks-3.13.2, rspec-support-3.13.2, json-2.9.0, regexp_parser-2.9.3, rubocop-ast-1.37.0, unicode-display_width-3.1.2, addressable-2.8.7, xpath-3.2.0, rexml-3.4.0, rubyzip-2.3.2, websocket-1.2.11, minitest-5.25.4, mutex_m-0.3.0, securerandom-0.4.1, date-3.4.1, timeout-0.4.3, zeitwerk-2.7.1, rackup-2.2.1, execjs-2.10.0, rdoc-6.9.1, io-console-0.8.0, unicode-emoji-4.0.4, public_suffix-6.0.1, psych-5.2.1, stringio-3.1.2 in locally installed gems (Bundler::GemNotFound)
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:193:in `specs'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/definition.rb:259:in `specs_for'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/runtime.rb:18:in `setup'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler.rb:164:in `setup'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/setup.rb:32:in `block in <top (required)>'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/ui/shell.rb:159:in `with_level'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/ui/shell.rb:111:in `silence'
2025-01-04 02:16:36 08:16:36 css.1  |   from /usr/local/bundle/gems/bundler-2.5.16/lib/bundler/setup.rb:32:in `<top (required)>'
2025-01-04 02:16:36 08:16:36 css.1  |   from <internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:88:in `require'
```

2025-01-04 08:34 UTC, aksafan commented
Will try to figure out what is going on tomorrow.

2025-01-04 19:07 UTC, aksafan commented
@VoldemLive 
I fixed infra issue, reset everything and got back to testing your code.

When I try to add Lab Test as a user (not a user role) without no assigned clients I see this empty dropdown:
![image](https://github.com/user-attachments/assets/1af7369a-bfb2-4833-a8a9-980cb9865a04)
You can use this [helper](https://github.com/Code-the-Dream-School/health-keeper/blob/38f1a5552d812d7cca1c7c88e7b51b97f916c20a/app/helpers/users_helper.rb#L53) to not show that empty dropdown.
 
After that I got this error on saving:
![image](https://github.com/user-attachments/assets/ec370d4d-3f91-417b-a0a8-0e41919bb278)


The same error I got when trying to create Lab Test with assigned user:
![image](https://github.com/user-attachments/assets/3e06749d-278d-4908-bfb3-b87da64709ae)

2025-01-04 19:16 UTC, aksafan commented on app/views/lab_tests/new.html.erb
> +              assigned_users_list_for_select(current_user, @lab_test.user || current_user)
I didn't get why do you trying to pass `@lab_test.user` as a current user here?

2025-01-04 19:21 UTC, aksafan commented
> @VoldemLive I fixed infra issue, reset everything and got back to testing your code.
> 
> When I try to add Lab Test as a user (not a user role) without no assigned clients I see this empty dropdown: ![image](https://private-user-images.githubusercontent.com/14964793/400159687-1af7369a-bfb2-4833-a8a9-980cb9865a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTg1MzMsIm5iZiI6MTczNjAxODIzMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNTk2ODctMWFmNzM2OWEtYmZiMi00ODMzLWE4YTktOTgwY2I5ODY1YTA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MTFkMjU0YmQzMWFjZDc5OTk4ODFlYzFlMjdhYmJkZTJhM2U0NjlkY2EwYjgyMDcyZDExNGM1ZGNjMjkxOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.F5Ir4lvAVUdtf9ILDDVUH4FUtCZKDjLWBi-1n11Bc0s) You can use this [helper](https://github.com/Code-the-Dream-School/health-keeper/blob/38f1a5552d812d7cca1c7c88e7b51b97f916c20a/app/helpers/users_helper.rb#L53) to not show that empty dropdown.
> 
> After that I got this error on saving: ![image](https://private-user-images.githubusercontent.com/14964793/400159788-ec370d4d-3f91-417b-a0a8-0e41919bb278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTg1MzMsIm5iZiI6MTczNjAxODIzMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNTk3ODgtZWMzNzBkNGQtM2Y5MS00MTdiLWEwYTgtMGU0MTkxOWJiMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlM2VkZWUwODljNzE3Y2Q5MmIwZGNiOTZmZjc1M2NkNjViMWExYjZmZDliZjE2Yjc4YjliOWNmM2U3MjY2OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rkuxU4y9jt9U4jRQgdVNIWPI11BU0Kja77ag4RBSThU)
> 
> The same error I got when trying to create Lab Test with assigned user: ![image](https://private-user-images.githubusercontent.com/14964793/400159852-3e06749d-278d-4908-bfb3-b87da64709ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYwMTg1MzMsIm5iZiI6MTczNjAxODIzMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNTk4NTItM2UwNjc0OWQtMjc4ZC00OTA4LWJmYjMtYjg3ZGE2NDcwOWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA0VDE5MTcxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMGZiYWFkMmEyOGMxZGQxMDlhNzNhZDQxNjhiOTgzZTU0ZDY1M2UzOGVkZWJhZGVkNjFlZWY4MDVhMmYzMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fkhiis9rawSfSHklsJqzlp31jwQYdW96hIHktA02oTQ)

@VoldemLive 
I have found a root cause of that error for you:
- when you are handling an error response [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR68), you are trying to load error dependencies [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR117) and then you don't have `@biomarkers` [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR128) as they are [set](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR133) only in `set_biomarkers` that are [called](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR8) only for `%i[index new edit]` actions (and you are calling all of these from a `create` action).

2025-01-04 19:28 UTC, aksafan commented
BTW, these two functions are called 2 times one after another when the first `handle_error_response` is called.
![image](https://github.com/user-attachments/assets/04f978b0-1f8c-4f02-97f2-d74802fcf56b)

In other words, you are doing the same logic and doing the same queries to DB twice.

2025-01-04 19:33 UTC, aksafan commented on app/controllers/lab_tests_controller.rb
> +    @reference_ranges = @selected_biomarker.reference_ranges
Why do you assign `@reference_ranges` here if you don't use it anywhere?

2025-01-04 20:27 UTC, aksafan commented
When showing validation errors, there is an inconsistent message for the value field and there is a duplication of error messages on a page:
![image](https://github.com/user-attachments/assets/480f76c2-9325-4191-9ba7-f14ca686d4d8)

2025-01-05 03:37 UTC, aksafan commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
Don't add this please.

My previous code (without current user by default) was added on purpose.

You don't want to show a dropdown with the only one current user option inside. This doesn't make sense as we have already had current user logged in an he or she should see his or her data or create a record from his or her user_id by default.

Moreover, adding current user to an empty assignment users list is misleading as in that case current user is not really assigned to himself.

2025-01-05 03:41 UTC, aksafan commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
I added current user to a list of assigned users just as a temporary solution for current user to be able to see/add lab tests as well (not only for assigned users).

This should be rethought in the future. I am going to work on that, but for now the current solution is a way to go.
There is a TODO for this [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-0a32d4e9f83e8c59487817bce4ccece334edc27596e9c7c9e8e2888ed4b0fc97R36).

2025-01-05 19:15 UTC, VoldemLive commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
As I answer to you in Slack, "Hmm… and “yes” and “no.” For example, take a table with lab tests, at one moment, you need to design a filter component with a drop-down with a users and date selection and another one without a users dropdown. I don’t think this is a good practice." 
My position is different. I think the user needs to see himself in the drop-down list. Even in the release, it will be possible for him to enter lab tests for himself. Rendering the dropdown with a single value is not a good idea, but we can convert it to a text field, and we will leave the element in the same position without huge differences (two columns, three columns).

2025-01-05 19:18 UTC, VoldemLive commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
@aksafan, could you please review and merge this branch? We need to move further.

2025-01-05 23:27 UTC, aksafan commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
> My position is different. I think the user needs to see himself in the drop-down list. Even in the release, it will be possible for him to enter lab tests for himself. Rendering the dropdown with a single value is not a good idea, but we can convert it to a text field, and we will leave the element in the same position without huge differences (two columns, three columns).

@VoldemLive 

We have two situations:
1) User with user role creates a Lab test:
![image](https://github.com/user-attachments/assets/d8ce8bc5-d41b-4b01-9cde-41de7929a11e)

2) User with admin/doctor/hc role creates a Lab test:
![image](https://github.com/user-attachments/assets/5eaba50f-1940-45e3-b8e4-a083268fddfc)

From the customer point of view - both of these cases are the same.
Than, why do you wan to make them behave differently?

2025-01-05 23:31 UTC, aksafan commented on app/helpers/users_helper.rb
> +    return [current_user.full_name] if user.assigned_users.empty?
> @aksafan, could you please review and merge this branch? We need to move further.

@VoldemLive I did a review yesterday and even sent you a list of not answered comments:
![image](https://github.com/user-attachments/assets/db73229b-51d1-407f-8a4b-b6f16a022874)

So from my point of view, I don't block anything.

I'm fully agree than we need to move forward, but merging buggy and inconsistent functionality is not the way it works in software engineering.

So, again, here is a list of comments to address (or at least to answer):
[here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1903141495);
[here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571388466);
[here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571390345);
[here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#discussion_r1903142955);
[here](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571403714).

2025-01-06 00:04 UTC, VoldemLive commented on app/controllers/lab_tests_controller.rb
> +    @reference_ranges = @selected_biomarker.reference_ranges
you are right, it's an extra line. Deleted.

2025-01-06 00:39 UTC, VoldemLive commented
> When showing validation errors, there is an inconsistent message for the value field and there is a duplication of error messages on a page: ![image](https://private-user-images.githubusercontent.com/14964793/400163248-480f76c2-9325-4191-9ba7-f14ca686d4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMjI3MDMsIm5iZiI6MTczNjEyMjQwMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNjMyNDgtNDgwZjc2YzItOTMyNS00MTkxLTliYTctZjE0Y2E2ODZkNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmFiNDczYmI4NzAzMDAxODYxNjZhZmQ2ZmNhNjFkZjAyYWJmYzYxNmQxODZiY2E0NTAxZTZkMjIwYjc0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q35E2uzDb6I76Js-7dMCxk1S0FvMDQYP5dTpWAXEF8Y)

removed additional error label

2025-01-06 00:45 UTC, VoldemLive commented on app/views/lab_tests/new.html.erb
> +              assigned_users_list_for_select(current_user, @lab_test.user || current_user)
this part is rewritten.

2025-01-06 00:46 UTC, aksafan commented
> > When showing validation errors, there is an inconsistent message for the value field and there is a duplication of error messages on a page: ![image](https://private-user-images.githubusercontent.com/14964793/400163248-480f76c2-9325-4191-9ba7-f14ca686d4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMjI3MDMsIm5iZiI6MTczNjEyMjQwMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNjMyNDgtNDgwZjc2YzItOTMyNS00MTkxLTliYTctZjE0Y2E2ODZkNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmFiNDczYmI4NzAzMDAxODYxNjZhZmQ2ZmNhNjFkZjAyYWJmYzYxNmQxODZiY2E0NTAxZTZkMjIwYjc0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q35E2uzDb6I76Js-7dMCxk1S0FvMDQYP5dTpWAXEF8Y)
> 
> removed additional error label

@VoldemLive Well done!

So only [set_user issue](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571388466) left.

2025-01-06 00:54 UTC, VoldemLive commented
> > > When showing validation errors, there is an inconsistent message for the value field and there is a duplication of error messages on a page: ![image](https://private-user-images.githubusercontent.com/14964793/400163248-480f76c2-9325-4191-9ba7-f14ca686d4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMjI3MDMsIm5iZiI6MTczNjEyMjQwMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNjMyNDgtNDgwZjc2YzItOTMyNS00MTkxLTliYTctZjE0Y2E2ODZkNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmFiNDczYmI4NzAzMDAxODYxNjZhZmQ2ZmNhNjFkZjAyYWJmYzYxNmQxODZiY2E0NTAxZTZkMjIwYjc0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q35E2uzDb6I76Js-7dMCxk1S0FvMDQYP5dTpWAXEF8Y)
> > 
> > 
> > removed additional error label
> 
> @VoldemLive Well done!
> 
> So only [set_user issue](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571388466) left.

got it and fixed.

2025-01-06 01:00 UTC, aksafan commented
> > > > When showing validation errors, there is an inconsistent message for the value field and there is a duplication of error messages on a page: ![image](https://private-user-images.githubusercontent.com/14964793/400163248-480f76c2-9325-4191-9ba7-f14ca686d4d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxMjI3MDMsIm5iZiI6MTczNjEyMjQwMywicGF0aCI6Ii8xNDk2NDc5My80MDAxNjMyNDgtNDgwZjc2YzItOTMyNS00MTkxLTliYTctZjE0Y2E2ODZkNGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA2VDAwMTMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5NmFiNDczYmI4NzAzMDAxODYxNjZhZmQ2ZmNhNjFkZjAyYWJmYzYxNmQxODZiY2E0NTAxZTZkMjIwYjc0ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.q35E2uzDb6I76Js-7dMCxk1S0FvMDQYP5dTpWAXEF8Y)
> > > 
> > > 
> > > removed additional error label
> > 
> > 
> > @VoldemLive Well done!
> > So only [set_user issue](https://github.com/Code-the-Dream-School/health-keeper/pull/23#issuecomment-2571388466) left.
> 
> got it and fixed.

@VoldemLive where?
It still in [code](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR133):
![image](https://github.com/user-attachments/assets/601338bb-61d9-4906-bd50-64b5a2c291ae)

2025-01-06 01:09 UTC, VoldemLive commented
> The error appears when you haven't set a user properly [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR59).
> This happens cause [here](https://github.com/Code-the-Dream-School/health-keeper/pull/23/files#diff-f7fcfdbad10e32bb265e9ba7415ebc17190f6dbd815cca2caeed74a00af4b6efR145) you have nil in params[:user_id] and you can't call nil.present?.
> And this happens cause there is no user_id in params, there is only lab_test in params and user_id is inside that lab_test:

you are right, rewrited:
`  def set_user
    if current_user.full_access_roles_can?
      User.find(lab_test_params[:user_id])
    else
      current_user
    end
  end`
  
  in a few sec will push fixes

2025-01-06 01:14 UTC, aksafan commented
> def set_user if current_user.full_access_roles_can? User.find(lab_test_params[:user_id]) else current_user end end

@VoldemLive Great!

One question: what if there is no `user_id` in `lab_test_params` or  `lab_test_params[:user_id]` is empty?
I assume, that check won't work.

What do you think about this?

```ruby
  def set_user
    if current_user.full_access_roles_can? && lab_test_params[:user_id].present?
      User.find(lab_test_params[:user_id])
    else
      current_user
    end
  end
```

2025-01-06 01:17 UTC, VoldemLive commented
> One question: what if there is no `user_id` in `lab_test_params` or `lab_test_params[:user_id]` is empty? I assume, that check won't work.
> 
> What do you think about this?

hmm ... we still need to check it in "if" before, or we will crach the app

2025-01-06 01:18 UTC, aksafan commented
> > One question: what if there is no `user_id` in `lab_test_params` or `lab_test_params[:user_id]` is empty? I assume, that check won't work.
> > What do you think about this?
> 
> hmm ... we still need to check it in "if" before, or we will crach the app

Exactly!

2025-01-06 01:30 UTC, aksafan commented
@VoldemLive Well done with all of fixes and changes!

Huge gratz on merging your first pull request!
I'm proud of your stamina and agility!

2025-01-06 01:31 UTC, aksafan approved these changes

2025-01-06 01:32 UTC, merged

2025-01-06 01:33 UTC, VoldemLive commented
> @VoldemLive Well done with all of fixes and changes!
> 
> Huge gratz on merging your first pull request! I'm proud of your stamina and agility!

Thanks to Anton for his persistence and patience in helping beginners. I need to drink ))))))